### ISSUE TITLE
How can i apply pulltorefresh for the JazzyListView library.

### ISSUE THREAD

**Issue by nanibabu** [twotoasters/JazzyListView#24]
Hi,
    I need to apply pulltorefresh and as well JazzyListView animation to the listview . how can i apply.

**Comment by jbarr21** [comment]
There should be no issue. Just setup your listview with JazzyListView and wrap that listview in a [SwipeRefreshLayout](https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html)
