### ISSUE TITLE
How to install this library into my project?

### ISSUE THREAD

**Issue by masbagus** [twotoasters/JazzyListView#25]
Hi twotoasters..

I just knew your awesome library (JazzyListView) from "Libraries for developers" application I downloaded on Play Store.
Therefore I want to install it in my project. But I don't understand how to do that.
So, could you tell me how to install your library into my application's project?
Details explanation would be nice for me. Sorry for this, because I'm still newbie.

That's all I want to know.
Your answers will be expected.

**Comment by jbarr21** [comment]
Have a look at the [sample app](https://github.com/twotoasters/JazzyListView/blob/master/sample/src/com/twotoasters/jazzylistview/sample/SimpleListActivity.java), that should show you everything you need to know.

**Comment by masbagus** [comment]
But when I tried to import your app (JazzyListView), it went to error and give me message:
1. Unlinked gradle project
2. Could not connect to maven
What should I do to fix these errors?
