### ISSUE TITLE
Still Error

### ISSUE THREAD

**Issue by masbagus** [twotoasters/JazzyListView#26]
![error_as](https://cloud.githubusercontent.com/assets/10800049/6015960/8f5237a2-abad-11e4-9aad-f3d8a7258ef6.jpg)
Hi..
I still got the error when try to use your app in Android Studio.
What should I do. Please tell me the easiest way..

**Comment by jbarr21** [comment]
PR #28 should add support for Android Gradle plugin 1.0.x
