### ISSUE TITLE
I have no idea how to use your library into my project

### ISSUE THREAD

**Issue by masbagus** [twotoasters/JazzyListView#27]
I got this error when I was trying to use your 'library' module.

![error_as](https://cloud.githubusercontent.com/assets/10800049/6057150/37285cb8-ad4d-11e4-96e2-f190bd91471f.jpg)

So, would you like to tell me the easiest tutorial how to do it.
Please, I'm begging on you..

**Comment by chris2toasters** [comment]
What version of Android Studio are you using? What version of the Android Gradle plugin?  What version is your gradle wrapper? I would guess that you are on the super old preview stuff, which may not have an auto upgrade path to 1.0.+. If I'm right, you're going to burn a day upgrading but do it.

**Comment by chris2toasters** [comment]
I'm closing this as an issue but we'll continue to talk.

**Comment by masbagus** [comment]
I'm using 
- Android Studio 1.0.2
- Gradle version 2.2.1
- Gradle wrapper I don't know what version. I set it to default in Settings.

So, could you just tell me the easiest tutorial of how to make your lib work on my project?
I've seen your lib is using Maven based project which I don't know well. I've tried many ways but all went error. I almost give up :(

Sorry for bad English.
