### ISSUE TITLE
Could not find property 'BINTRAY_USER'

### ISSUE THREAD

**Issue by Ferdosi** [twotoasters/JazzyListView#31]
Could not find property 'BINTRAY_USER' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@3c9c63d1.

**Comment by jbarr21** [comment]
this is just used for building. you should be just able to comment out L20 of build.gradle in library folder...

`apply from: '../gradle-bintray-push.gradle'`

**Comment by jbarr21** [comment]
@Ferdosi this should be fixed on master now without you needing to make any additional changes

**Comment by Ferdosi** [comment]
thanks a lot jbarr21

On Tue, Mar 3, 2015 at 1:05 AM, jbarr21 <notifications@github.com> wrote:

> @Ferdosi <https://github.com/Ferdosi> this should be fixed on master now
> without you needing to make any additional changes
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/twotoasters/JazzyListView/issues/31#issuecomment-76830350>
> .
>



-- 

Mohammadreza razzaghi Taheri

Ferdosi Media AB Technical manager

razzaghi@ferdosi.com
