### ISSUE TITLE
Customize animation duration

### ISSUE THREAD

**Issue by sbaar** [twotoasters/JazzyListView#35]
600 ms is too long and not really standard in other animations which are usually 200-300ms. It should be customizable. Since duration is in the JazzyHelper class I don't really know where the best place to make the modification would be, but making it not final would be a start. As of now I'll just have to include the library source manually.

**Comment by jbarr21** [comment]
i agree 600ms is too long, i think that value was used more for display purposes so you could see the effects.  i'll look into reducing that value.  but, that value is just a default.  you don't need to include the library source, all you need to do is create your own jazzy effect (or copy one from this repo). then, in `JazzyEffect.setupAnimation`, set your desired duration on the `animator` that is passed in

**Comment by sbaar** [comment]
Thanks, that works great and is a good place to put in an interpolator too. By the way, By the way I think PR #28 fixed the npe issue I was having.
