### ISSUE TITLE
Jazzy List View with Recycler View

### ISSUE THREAD

**Issue by sujaykumarh** [twotoasters/JazzyListView#50]
this works 

recyclerView.setAdapter(adapter);
JazzyRecyclerViewScrollListener listener = new JazzyRecyclerViewScrollListener();
listener.setTransitionEffect(new SlideInEffect());
recyclerView.setOnScrollListener(listener);

this does not from the readme

recyclerView.setTransitionEffect(new SlideInEffect());

**Comment by splm** [comment]
that's right.i've read the source code of JazzxxListener.
